# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Port -> adapter (write repo)
    App\Person\Domain\Repository\PersonRepository:
        class: App\Person\Infrastructure\Doctrine\DoctrinePersonRepository
        autowire: true

    # Shared buses (wrappery na Messenger)
    App\Shared\Application\Bus\CommandBus:
        class: App\Shared\Infrastructure\Bus\MessengerCommandBus
        arguments: ['@messenger.bus.default']
        autowire: true

    App\Shared\Application\Bus\QueryBus:
        class: App\Shared\Infrastructure\Bus\MessengerQueryBus
        arguments: ['@messenger.bus.default']
        autowire: true


    # Ports -> adapters
    App\Identity\Domain\Repository\UserAccountRepository:
        class: App\Identity\Infrastructure\Doctrine\DoctrineUserAccountRepository
        autowire: true

    App\Identity\Domain\Repository\AuthMethodRepository:
        class: App\Identity\Infrastructure\Doctrine\DoctrineAuthMethodRepository
        autowire: true

    App\Identity\Domain\Repository\PasswordCredentialRepository:
        class: App\Identity\Infrastructure\Doctrine\DoctrinePasswordCredentialRepository
        autowire: true

    App\Identity\Application\Port\PersonLookup:
        class: App\Identity\Infrastructure\Person\DbalPersonLookup
        autowire: true

    App\Identity\Infrastructure\Security\GoogleOidcClient:
        arguments:
            $googleClientId: '%env(GOOGLE_OAUTH_CLIENT_ID)%'
